routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/doctors', 'HomeController@doctors')->name('doctors');

Route::get('/services', 'HomeController@services')->name('services');

Route::get('/contact', 'HomeController@contact')->name('contact');

Route::resource('blogs', 'BlogController');

Route::get('/pricing', 'HomeController@pricing')->name('pricing');

Route::get('/history', 'HomeController@history')->name('history');

Route::get('/appointment', 'AppointmentController@index')->name('appointment');

Route::post('/appointment', 'AppointmentController@store')->name('appointments.store');

Route::get('/maps', 'AppointmentController@maps');

// admin page
Route::middleware(['auth'])->prefix('admin')->group(function () {

    Route::get('home', 'Admin\HomeController@index')->name('admin.home');

    Route::resource('doctors', 'Admin\DoctorController', ['as' => 'admin']);

    Route::resource('specialist', 'Admin\SpecialistController', ['as' => 'admin']);

    Route::resource('blogs', 'Admin\BlogController', ['as' => 'admin']);

    Route::resource('appointments', 'Admin\AppointmentController', ['as' => 'admin']);
});

app/Specialist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Specialist extends Model
{
    protected $fillable = ['name', 'remark'];
}

app/Http/Controllers/Admin/SpecialistController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\SpecialistRequest;
use App\Specialist;
use Illuminate\Http\Request;

class SpecialistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $specialists = Specialist::paginate(20);
        return view('admin.specialist.index', compact('specialists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.specialist.create');    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SpecialistRequest $request)
    {
        $data = $request->validated();

        Specialist::create($data);

        return redirect()->route('admin.specialist.index')->with('success', 'Ok, Successfully inserted.');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function show(Specialist $specialist)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function edit(Specialist $specialist)
    {
        return view('admin.specialist.edit', compact('specialist'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function update(SpecialistRequest $request, Specialist $specialist)
    {
        $data = $request->validated();

        $specialist->update($data);

        return redirect()->route('admin.specialist.index')->with('success', 'Ok, Successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Specialist $specialist)
    {
        $specialist->delete();
        return redirect()->route('admin.specialist.index')->with('success', 'Ok, Successfully Deleted.');
    }
}

app/Http/Controllers/SpecialistController.php
<?php

namespace App\Http\Controllers;

use App\Specialist;
use Illuminate\Http\Request;

class SpecialistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function show(Specialist $specialist)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function edit(Specialist $specialist)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Specialist $specialist)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Specialist  $specialist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Specialist $specialist)
    {
        //
    }
}

resources/views/admin/specialist/create.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
              <li class="breadcrumb-item"><a href="{{ route("admin.doctors.index") }}">Specialist List</a></li>
              <li class="breadcrumb-item active" aria-current="page">Create</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-3">
            <div class="row">
                <div class="col-lg-10 p-3 mb-2 bg-secondary text-white text-center">Create Specialist</div>
                <div class="col-md-10">
                    <form action="{{ route('admin.specialist.store') }}" class="ftco-animate" method="POST">
                        @csrf
                        @method('POST')
                        <div class="d-md-flex">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Name" name="name">
                            </div>
                            <div class="form-group ml-md-4">
                                <input type="text" class="form-control" placeholder="Remark" name="remark">
                            </div>
                        </div>

                        <div class="d-md-flex">
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-secondary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/specialist/edit.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route("admin.specialist.index") }}">Specialist List</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Doctor</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-3">
            <div class="row">
                <div class="col-lg-10 p-3 mb-2 bg-secondary text-white text-center">Create Doctor</div>
                <div class="col-md-10">
                    <form action="{{ route('admin.specialist.update' , ['specialist' => $specialist]) }}" class="ftco-animate" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span>Name</div>
                                    <input type="text" class="form-control" placeholder="Name" name="name" value="{{ old('name') ? old('name') : $specialist->name }}">
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span>Degree</div>
                                    <input type="text" class="form-control" placeholder="remark" name="remark" value="{{ old('remark') ? old('remark') : $specialist->remark }}">
                                </div>
                            </div>
                        </div>

                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <input type="submit" value="Update" class="btn btn-secondary">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/specialist/index.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">DashBoard</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-5">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        {{ __('Doctors List') }}
                        <span class="float-right">
                            <button class="btn btn-success"><a href="{{ route("admin.specialist.create") }}" class="p-3 text-dark"> + New</a></button>
                        </span>
                    </div>

                    <div class="card-body">

                        <div class="table table-responsive">

                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Remark</th>
                                        <th colspan="2">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($specialists as $index=>$doctor)
                                        <tr>
                                            <td class="text-right">{{ ++$index }}</td>
                                            <td class="">{{ $doctor->name }}</td>
                                            <td class="">{{ $doctor->remark }}</td>
                                            <td>
                                                <a href="{{ route("admin.specialist.edit", ["specialist" => $doctor]) }}" class="btn btn-md btn-info">Edit</a>
                                            </td>
                                            <td>
                                                <form action="{{ route("admin.specialist.destroy", ["specialist" => $doctor])}}" method="POST">
                                                    @csrf
                                                    @method("DELETE")
                                                        <button class="btn btn-md btn-danger" onclick="return confirm('Are You Sure want to delete?')">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>

                    </div>
                    <div class="card-footer">
                        {{$specialists->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection