routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/doctors', 'HomeController@doctors')->name('doctors');

Route::get('/services', 'HomeController@services')->name('services');

Route::get('/contact', 'HomeController@contact')->name('contact');

Route::resource('blogs', 'BlogController');

Route::get('/pricing', 'HomeController@pricing')->name('pricing');

Route::get('/history', 'HomeController@history')->name('history');

Route::get('/appointment', 'AppointmentController@index')->name('appointment');

Route::post('/appointment', 'AppointmentController@store')->name('appointments.store');

Route::get('/maps', 'AppointmentController@maps');

// admin page
Route::middleware(['auth'])->prefix('admin')->group(function () {

    Route::get('home', 'Admin\HomeController@index')->name('admin.home');

    Route::resource('doctors', 'Admin\DoctorController', ['as' => 'admin']);

    Route::resource('specialist', 'Admin\SpecialistController', ['as' => 'admin']);

    Route::resource('blogs', 'Admin\BlogController', ['as' => 'admin']);

    Route::resource('appointments', 'Admin\AppointmentController', ['as' => 'admin']);
});

app/Doctor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    protected $fillable = ['name', 'degree', 'mobile', 'licence_no', 'image_name', 'image_path', 'licence_expired_date', 'age', 'start_time', 'end_time', 'experience', 'specialist_id', 'created_by', 'updated_by', 'remark'];

    public function specialist()
    {
        return $this->belongsTo(Specialist::class);
    }
}

app/Http/Controllers/Admin/DoctorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Doctor;
use App\Http\Controllers\Controller;
use App\Http\Requests\DoctorRequest;
use App\Specialist;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $doctors = Doctor::paginate(20);
        return view('admin.doctors.index', compact("doctors"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $specialists = Specialist::all();

        return view('admin.doctors.create', compact('specialists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DoctorRequest $request)
    {
        $data = $request->validated();

        $data['created_by'] = auth()->user()->id;

        unset($data['licence_expired_date']); //delete licence_expired_date array value

        $data['licence_expired_date'] = date("Y-m-d", strtotime($request->licence_expired_date)); //set value again

        $doctor = Doctor::create($data);

        if (request('image_name')) {

            $imagePath = request('image_name')->store('doctors', 'public');

            $image = Image::make(public_path("storage/{$imagePath}"))->fit(700, 700);

            // $image->save();

            $imageArray = ['image_path' => $imagePath, 'image_name' => $image];

            $imageArray = array_merge($imageArray, ['image_name' => $image->basename]);

            $doctor->update($imageArray);
        }

        return redirect()->route('admin.doctors.index')->with('success', 'Ok, Successfully inserted.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function show(Doctor $doctor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function edit(Doctor $doctor)
    {
        $specialists = Specialist::all();

        return view('admin.doctors.edit', compact('doctor', 'specialists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function update(DoctorRequest $request, Doctor $doctor)
    {
        $data = $request->validated();

        $data['updated_by'] = auth()->user()->id;

        unset($data['licence_expired_date']); //delete licence_expired_date array value

        $data['licence_expired_date'] = date("Y-m-d", strtotime($request->licence_expired_date)); //set value again

        if (request('image_name')) {

            $file = "public/doctors/" . $doctor->image_name; //get existing file path

            Storage::delete($file); //delete existing file

            $imagePath = request('image_name')->store('doctors', 'public');

            $image = Image::make(public_path("storage/{$imagePath}"))->fit(300, 300);

            $image->save();

            $imageArray = ['image_path' => $imagePath];

            $imageArray = array_merge($imageArray, ['image_name' => $image->basename]);
        }

        $doctor->update(array_merge(
            $data,
            $imageArray ?? []
        ));

        return redirect()->route('admin.doctors.index')->with('success', 'Ok, Successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Doctor $doctor)
    {
        if ($doctor->image_name) {
            $file = "public/{$doctor->image_path}"; //get existing file path

            Storage::delete($file); //delete existing file
        }

        $doctor->delete();

        return redirect()->route('admin.doctors.index')->with('success', 'Ok, Successfully Deleted.');
    }
}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;

use App\Doctor;
use Illuminate\Http\Request;

class DoctorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function show(Doctor $doctor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function edit(Doctor $doctor)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Doctor $doctor)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Doctor  $doctor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Doctor $doctor)
    {
        //
    }
}

resources/views/admin/doctors/create.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
              <li class="breadcrumb-item"><a href="{{ route("admin.doctors.index") }}">Doctors List</a></li>
              <li class="breadcrumb-item active" aria-current="page">Create</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-3">
            <div class="row">
                <div class="col-lg-10 p-3 mb-2 bg-secondary text-white text-center">Create Doctor</div>
                <div class="col-md-10">
                    <form action="{{ route('admin.doctors.store') }}" class="ftco-animate" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="d-md-flex">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Name" name="name" value="{{ old("name") }}">
                            </div>
                            <div class="form-group ml-md-4">
                                <input type="text" class="form-control" placeholder="Degree" name="degree" value="{{ old("degree") }}">
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-phone-portrait"></span></div>
                                        <input type="text" class="form-control" placeholder="Phone" name="mobile" value="{{ old("mobile") }}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                    <input type="text" class="form-control" placeholder="Licence No" name="licence_no" value="{{ old("licence_no") }}">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span></div>
                                    <input type="text" class="appointment_date form-control" placeholder="Licence Expired Date" name="licence_expired_date" value="{{ old("licence_expired_date") }}">
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-md-calendar"></span></div>
                                    <input type="number" class="form-control" placeholder="Age" name="age" min="0" value="{{ old("age") }}">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-clock"></span></div>
                                    <input type="text" class="form-control appointment_time" placeholder="Start Time" name="start_time">
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-clock"></span></div>
                                    <input type="text" class="form-control appointment_time" placeholder="End Time" name="end_time" >
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-image"></span></div>
                                    <input type="file" class="form-control" name="image_name">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <select name="specialist_id" id="" class="form-control col-md-9">
                                <option value="">Select specialist</option>
                                @foreach ($specialists as $specialist)
                                    <option value="{{$specialist->id}}" >{{$specialist->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group row">
                                <div class="col-md-10">
                                    <div class="icon"><span class="ion-ios-text"></span></div>
                                    <div class="select-wrap">
                                        <textarea name="remark" id="" cols="30" rows="5" class="form-control" placeholder="remark">{{ old("remark") }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group ml-md-4 justify-content-center">
                                <div class="input-wrap my-2">
                                    <input type="submit" value="Create" class="btn btn-secondary ">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/doctors/edit.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route("admin.doctors.index") }}">Doctors List</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Doctor</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-3">
            <div class="row">
                <div class="col-lg-10 p-3 mb-2 bg-secondary text-white text-center">Update Doctor</div>
                <div class="col-md-10">
                    <form action="{{ route('admin.doctors.update' , ['doctor' => $doctor]) }}" class="ftco-animate" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span>Name</div>
                                    <input type="text" class="form-control" placeholder="Name" name="name" value="{{ old('name') ? old('name') : $doctor->name }}">
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span>Degree</div>
                                    <input type="text" class="form-control" placeholder="Degree" name="degree" value="{{ old('degree') ? old('degree') : $doctor->degree }}">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-phone-portrait"></span>Mobile</div>
                                        <input type="text" class="form-control" placeholder="Phone" name="mobile" value="{{ old('mobile') ? old('mobile') : $doctor->mobile }}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-arrow-down"></span>Licence No</div>
                                    <input type="text" class="form-control" placeholder="Licence No" name="licence_no" value="{{ old('licence_no') ? old('licence_no') : $doctor->licence_no }}">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span>Licence Expired Date</div>
                                    <input type="text" class="appointment_date form-control" placeholder="Licence Expired Date" name="licence_expired_date" value="{{ old('licence_expired_date') ? old('licence_expired_date') : date("d/m/Y", strtotime($doctor->licence_expired_date)) }}">
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-clock"></span>Office Start Time</div>
                                    <input type="text" class="form-control appointment_time" placeholder="Start Time" name="start_time" value="{{ old('start_time') ? old('start_time') : $doctor->start_time }}">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-clock"></span>Office End Time</div>
                                    <input type="text" class="form-control appointment_time" placeholder="End Time" name="end_time" value="{{ old('end_time') ? old('end_time') : $doctor->end_time }}">
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios"></span>Specialist</div>
                                    <select name="specialist_id" id="" class="form-control">
                                        @foreach ($specialists as $specialist)
                                            <option value="{{ $specialist->id }}" {{ $doctor->specialist_id == $specialist->id ? 'selected' : '' }}>{{ $specialist->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-image"></span></div>
                                    <input type="file" class="form-control" name="image_name">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-md-calendar"></span>Age</div>
                                    <input type="number" class="form-control" placeholder="Age" name="age" min="0" value="{{ old('age') ? old('age') : $doctor->age }}">
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group row">
                                <div class="col-md-10">
                                    <div class="icon"><span class="ion-ios-text"></span></div>
                                    <div class="select-wrap">
                                        <textarea name="remark" id="" cols="30" rows="5" class="form-control">{{ $doctor->remark }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group ml-md-4 my-2">
                                <input type="submit" value="Update" class="btn btn-secondary ">
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/doctors/index.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">DashBoard</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-5">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        {{ __('Doctors List') }}
                        <span class="float-right">
                            <button class="btn btn-success"><a href="{{ route("admin.doctors.create") }}" class="p-3 text-dark"> + New</a></button>
                        </span>
                    </div>
    
                    <div class="card-body">
                        
                        <div class="table table-responsive">
    
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Degree</th>
                                        <th>Specialist</th>
                                        <th>Mobile Ph</th>
                                        <th>Licence No</th>
                                        <th colspan="2" class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($doctors as $index=>$doctor)
                                        <tr>
                                            <td class="text-right">{{ ++$index }}</td>
                                            <td class="">{{ $doctor->name }}</td>
                                            <td class="">{{ optional($doctor->specialist)->name }}</td>
                                            <td>{{ $doctor->degree }}</td>
                                            <td>{{ $doctor->mobile }}</td>
                                            <td>{{ $doctor->licence_no }}</td>
                                           
                                            <td>
                                                <a href="{{ route("admin.doctors.edit", ["doctor" => $doctor]) }}" class="btn btn-md btn-info px-3">Edit</a>
                                                
                                            </td>
                                            <td>
                                                <form action="{{ route("admin.doctors.destroy", ["doctor" => $doctor])}}" method="POST">
                                                    @csrf
                                                    @method("DELETE")
                                                        <button class="btn btn-md btn-danger px-3" onclick="return confirm('Are You Sure want to delete?')">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
    
                        </div>
    
                    </div>
                    <div class="card-footer">
                        {{$doctors->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection