routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/doctors', 'HomeController@doctors')->name('doctors');

Route::get('/services', 'HomeController@services')->name('services');

Route::get('/contact', 'HomeController@contact')->name('contact');

Route::resource('blogs', 'BlogController');

Route::get('/pricing', 'HomeController@pricing')->name('pricing');

Route::get('/history', 'HomeController@history')->name('history');

Route::get('/appointment', 'AppointmentController@index')->name('appointment');

Route::post('/appointment', 'AppointmentController@store')->name('appointments.store');

Route::get('/maps', 'AppointmentController@maps');

// admin page
Route::middleware(['auth'])->prefix('admin')->group(function () {

    Route::get('home', 'Admin\HomeController@index')->name('admin.home');

    Route::resource('doctors', 'Admin\DoctorController', ['as' => 'admin']);

    Route::resource('specialist', 'Admin\SpecialistController', ['as' => 'admin']);

    Route::resource('blogs', 'Admin\BlogController', ['as' => 'admin']);

    Route::resource('appointments', 'Admin\AppointmentController', ['as' => 'admin']);
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = ['date', 'title', 'body', 'title_image', 'specialist_id', 'path', 'view_count', 'file_name', 'created_by', 'updated_by'];

    public function specialist()
    {
        return $this->belongsTo(Specialist::class);
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'created_by');
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Blog;
use App\Http\Controllers\Controller;
use App\Http\Requests\BlogRequest;
use App\Specialist;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::orderBy("id", "desc")->paginate(20);
        return view('admin.blogs.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $specialists = Specialist::all();

        return view('admin.blogs.create', compact('specialists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogRequest $request)
    {
        $data = $request->validated();

        $data['created_by'] = auth()->user()->id;

        $data['updated_by'] = auth()->user()->id;

        unset($data['date']); //delete licence_expired_date array value

        $data['date'] = date("Y-m-d", strtotime($request->date)); //set value again

        $blog = Blog::create($data);

        if (!empty($data['title_image'])) {
            $file = $data['title_image'];

            $file_name = time() . '.' . $file->getClientOriginalExtension();

            $data['title_image'] = $file_name;

            $data['path'] = $file->storeAs('public/blogs/' . $blog->id, $file_name);

            $blog->update($data);
        }

        return redirect()->route('admin.blogs.index')->with('success', 'Ok, Successfully inserted.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        $specialists = Specialist::all();

        return view('admin.blogs.edit', compact('blog', 'specialists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(BlogRequest $request, Blog $blog)
    {
        $data = $request->validated();

        $data['updated_by'] = auth()->user()->id;

        unset($data['date']); //delete licence_expired_date array value

        $data['date'] = date("Y-m-d", strtotime($request->date)); //set value again

        $blog->update($data); //update the record

        if (!empty($data['title_image'])) {
            $file = "public/blogs/" . $blog->id . "/" . $blog->title_image; //get existing file path

            Storage::delete($file); //delete existing file

            $file = $data['title_image'];

            $file_name = time() . '.' . $file->getClientOriginalExtension(); //change file name

            $data['title_image'] = $file_name;

            $data['path'] = $file->storeAs('public/blogs/' . $blog->id, $file_name); //upload file to the server

            $blog->update($data);
        }

        return redirect()->route('admin.blogs.index')->with('success', 'Ok, Successfully inserted.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $folder = 'public/blogs/' . $blog->id;

        Storage::deleteDirectory($folder);; //delete existing file

        $blog->delete();

        return redirect()->route('admin.blogs.index')->with('success', 'Ok, Successfully Deleted.');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $blogs = Blog::orderBy("id", "desc")->paginate(5);

        return view('blogs', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        return view('blog_single', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        //
    }
}

resources/views/admin/blogs/create.blade.php
@extends('layouts.admin_master')

@section('css_file')
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@3.0.5/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
@endsection

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
              <li class="breadcrumb-item"><a href="{{ route("admin.doctors.index") }}">Posts List</a></li>
              <li class="breadcrumb-item active" aria-current="page">Create</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-3">
            <div class="col-lg-10 p-3 mb-2 bg-secondary text-white text-center">Create Posts</div>
            <div class="col-md-10">
                <form action="{{ route('admin.blogs.store') }}" class="ftco-animate" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                    <div class="d-md-flex">
                        <div class="col-md-10">
                            <div class="form-field">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-calendar"></span></div>
                                    <input type="text" class="form-control appointment_date" placeholder="Entry Date" value="{{ old("date") }}" name="date">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-md-flex">
                        <div class="col-md-10">
                            <div class="form-field">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-text"></span></div>
                                    <input type="text" class="form-control" placeholder="Blog title" name="title" value="{{ old("title") }}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-md-flex">
                        <div class="col-md-10">
                            <div class="form-field">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-image"></span></div>
                                    <input type="file" class="form-control" name="title_image">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-md-flex">
                        <div class="col-md-10">
                            <div class="form-field">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-text"></span></div>
                                    <select name="specialist_id" id="" class="form-control">
                                        <option value="">Select Blog Type</option>
                                        @foreach ($specialists as $specialist)
                                            <option value="{{$specialist->id}}">{{ $specialist->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-md-flex">
                        <div class="col-md-10">
                            <div class="form-field">
                                <div class="select-wrap">
                                    <div class="icon"><span class="ion-ios-text"></span></div>
                                    <textarea name="body" id="description" class="form-control">{{ old("body") }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-md-flex">
                        <div class="col-md-10 ml-md-4">
                            <div class="input-wrap my-3">
                                <input type="submit" value="Create" class="btn btn-secondary">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js_file')
    <script src="https://cdn.ckeditor.com/4.13.0/full-all/ckeditor.js"></script>
    <script>
        $(function(){
            // initialize ckeditor
            CKEDITOR.replace('description');
        })
    </script>

@endsection

resources/views/admin/blogs/edit.blade.php
@extends('layouts.admin_master')

@section('css_file')
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@3.0.5/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
@endsection

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route("admin.blogs.index") }}">Blogs List</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit Blog</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-3">
            <div class="row">
                <div class="col-md-12 p-3 mb-2 bg-secondary text-white text-center">Update Blog</div>
                <div class="col-md-12">
                    <form action="{{ route('admin.blogs.update' , ['blog' => $blog]) }}" class="ftco-animate" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        <div class="d-md-flex">
                            <div class="col-md-12">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-calendar"></span></div>
                                        <input type="text" class="form-control appointment_date" placeholder="Entry Date" name="date" value="{{ old('name') ? old('name') : date("d-m-Y", strtotime($blog->date)) }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="col-md-12">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-phone-portrait"></span></div>
                                        <input type="text" class="form-control" placeholder="Post title" name="title" value="{{ old('title') ? old('title') : $blog->title }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="col-md-12">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-image"></span></div>
                                        <input type="file" class="form-control" name="title_image">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="col-md-12">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-text"></span></div>
                                        <select name="specialist_id" id="" class="form-control">
                                            <option value="">Select Blog Type</option>
                                            @foreach ($specialists as $specialist)
                                                <option value="{{$specialist->id}}" {{$specialist->id == $blog->specialist_id ? 'selected' : ''}}>{{$specialist->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="col-md-12">
                                <div class="form-field">
                                    <div class="select-wrap">
                                        <div class="icon"><span class="ion-ios-phone-portrait"></span></div>
                                        <textarea name="body" id="description" class="form-control">{!! old('body') ? old('body') : $blog->body !!}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="col-md-12 ml-md-4">
                                <div class="input-wrap my-3">
                                    <input type="submit" value="Update" class="btn btn-secondary">
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js_file')
    <script src="https://cdn.ckeditor.com/4.13.0/full-all/ckeditor.js"></script>
    <script>
        $(function(){
            // initialize ckeditor
            CKEDITOR.replace('description');
        })
    </script>

@endsection

resources/views/admin/blogs/index.blade.php
@extends('layouts.admin_master')

@section('content')
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route("admin.home") }}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">DashBoard</li>
            </ol>
        </nav>
        <div class="row justify-content-center mt-5">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">
                        {{ __('Blogs List') }}
                        <div class="float-right">
                            <button class="btn btn-success"><a href="{{ route("admin.blogs.create") }}" class="p-3 text-dark"> + New</a></button>
                        </div>
                    </div>

                    <div class="card-body">

                        <div class="table table-responsive">

                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Date</th>
                                        <th>Title</th>
                                        <th>Blog Type</th>
                                        <th>Title Image</th>
                                        <th colspan="2" class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($blogs as $index=>$blog)
                                        <tr>
                                            <td class="text-right">{{ ++$index }}</td>
                                            <td class="">{{ date("d-M-Y", strtotime($blog->date)) }}</td>
                                            <td class="">{{ $blog->title }}</td>
                                            <td class="">{{ optional($blog->specialist)->name }}</td>
                                            <td class="">{{ $blog->title_image }}</td>
                                            <td>
                                                <a href="{{ route("admin.blogs.edit", ["blog" => $blog]) }}" class="btn btn-md btn-info">Edit</a>

                                            </td>
                                            <td>
                                                <form action="{{ route("admin.blogs.destroy", ["blog" => $blog])}}" method="POST">
                                                    @csrf
                                                    @method("DELETE")
                                                        <button class="btn btn-md btn-danger" onclick="return confirm('Are You Sure want to delete?')">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>

                    </div>
                    <div class="card-footer">
                        {{$blogs->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection